SELECT 'YOUNGEST', NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY = (SELECT MIN (BIRTHDAY)  FROM WORKER)  
UNION
SELECT 'OLDEST',  NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY=(SELECT MAX(BIRTHDAY)  FROM WORKER)  
ORDER BY  BIRTHDAY DESC;
